# Generated by Django 5.2.7 on 2025-10-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
